$LOAD_PATH.unshift(File.join(File.dirname(__FILE__), "..", "lib"))

ENV["TWITTER_CONSUMER_KEY"] = "TWITTER_CONSUMER_KEY"
ENV["TWITTER_CONSUMER_SECRET"] = "TWITTER_CONSUMER_SECRET"
ENV["TWITTER_ACCESS_TOKEN"] = "TWITTER_ACCESS_TOKEN"
ENV["TWITTER_ACCESS_TOKEN_SECRET"] = "TWITTER_ACCESS_TOKEN_SECRET"
