name: Run tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.7.x"

      - name: Install test dependencies
        run: |
          sudo apt-get install libmagickwand-dev
          bundle install --frozen --jobs 4 --retry 3 --without development

      - name: Run tests
        run: rake test
